### ISSUE TITLE
Plugin fails to load in Linux Mint 18.2 Totem 3.18

### ISSUE THREAD

**Issue by hornmich** [hornmich/totem-plugin-poweroff#1]
Traceback (most recent call last):
  File "/usr/lib/totem/plugins/poweroffplugin/poweroffplugin.py", line 134, in __init__
    self._sidePanel = SidePanel()
  File "/usr/lib/totem/plugins/poweroffplugin/poweroffplugin.py", line 51, in __init__
    self._buttons.append(Gtk.RadioButton.new_with_label_from_widget(self._buttons[0], _("Turn off computer")))
TypeError: Must be string, not bytes
Traceback (most recent call last):
  File "/usr/lib/totem/plugins/poweroffplugin/poweroffplugin.py", line 144, in do_activate
    self._totem.add_sidebar_page("poweroffSidePage", _("After playback stops"), self._sidePanel.getWidget())
AttributeError: 'StarterPlugin' object has no attribute '_sidePanel'

**Comment by hornmich** [comment]
Now the plugin is loaded, but since the side panel has been removed, it is not visible for the user.
The plugin needs to add a menu to the menu bar.
